# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "FarInHeight"
repo_name: "hyperbolic-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/hyperbolic-arxiv-daily.json'
json_gitpage_path: './docs/hyperbolic-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# filters and subcategories to search
filters: ["hyperbolic space", "hyperbolic network", "hyperbolic neural", "hyperbolic neural network"]
subcategories: [
    {"acronym": "cs.CV", "description": "Computer Vision and Pattern Recognition"},
    {"acronym": "cs.CL", "description": "Computation and Language"},
    {"acronym": "cs.LG", "description": "Machine Learning"},
    {"acronym": "cs.AI", "description": "Artificial Intelligence"},
]